### ISSUE TITLE
Correction

### ISSUE THREAD

**Issue by alexellis** [robshep/openfass-tests#1]
"Some simplistic testing for evaluating OpenFaas" -> "... OpenFaaS with Docker Swarm"

Docker Swarm is not recommended for testing, performance testing or production. 

For your use case of "automatic builds" you may prefer to use OpenFaaS Cloud which has built-in CI/CD. https://docs.openfaas.com/openfaas-cloud/intro/

Please see notes on:

A) Performance testing (about interaction with project and use of a realistic Kubernetes Cluster - i.e. cluster > single node) - https://docs.openfaas.com/architecture/performance/
B) Nodes on running in production should also be read - https://docs.openfaas.com/architecture/production/

Doing the build and deploy on the same single node isn't realistic or recommended. Timing the build on your own server is also quite odd.

I would suggest you build once and use an environment variable to print out the message from your loop. Using `faas-cli` to deploy would perhaps give a better experience than the bespoke Swagger client.

Alex

**Comment by robshep** [comment]
Thanks Alex.  

I'll be certain to absorb more of the excellent docs as we evaluate.  

I now realise the overhead of building cont images, but despite being unrealistic for you, this is 100% what we want to do, I'll take the 'odd' comment as a compliment. ;)
In this enormously crappy 1st test I just wanted to build as many simple little functions as I could and execute them. 
What I've learnt is that the overhead of building the images , and then unpacking them during the cold start is the overhead but doesn't impact on the warm execution. 
All of it is relevant to our proposed application though. And expecting considerable build churn.

My next test will be to cluster up separate build and exe hosts to isolate those two areas of the process and inspect them independently.

The swagger client (just dragged off editor.swagger.io, almost verbatim, works fine and means I can just do everything in vanilla python.

**Comment by alexellis** [comment]
The problem is that you have published faulty data that can lead people to the impression that "OpenFaaS" cannot scale and that it will crash. That's damaging and absolutely not true.

Docker Swarm is not a recommended production platform. Docker Swarm's health check mechanism is what created excessive CPU usage in Swarm, it can be turned off by removing HEALTHCHECK commands.
